language: php

php:
    - 7.3

before_script:
    - cp .env.travis .env
    - travis_retry composer install --no-interaction
    - php artisan key:generate
    - php artisan config:clear

script:
    - vendor/bin/phpunit